### ISSUE TITLE
DEMETER batch reconstruction pipeline 

### ISSUE THREAD

**Issue by AngelRuizMoreno** [opencobra/COBRA.papers#119]
Hi,

I'm trying to reproduce the DEMETER pipeline for AGORA2. To do so, I'm using the cobratoolbox in Matlab R2019a with CPLEX_Studio1210 as solver. 

My set-up seems to be correct because I can run the test and perform some task of the reconstruction in the tutorial.

The issue is in the section **2.2. Testing the refined reconstructions**. Every time I want to run this part and plotting some results for the ATP production, etc. I got the following error:

<img width="546" alt="image" src="https://github.com/opencobra/COBRA.papers/assets/34551143/c765b124-52d7-4eca-a567-b1b911a176d1">

I can't figure out what is the error because seems to be related to a header of the function **readtable**.

Could you tell me how to fix the error?

Thanks in advance.

**Comment by AngelRuizMoreno** [comment]
Hi, 

Yes, in total 21 text files were generated. After some search online, I discovered that the function readtable was different in Matlab R2019b and that was causing the problem. So, I upgraded Matlab to R2020b with CPLEX_Studio1210. After running the tutorial, The debugging is still unsuccessful but with different error message:

<img width="855" alt="image" src="https://github.com/opencobra/COBRA.papers/assets/34551143/b925983e-5baa-4083-8889-9f1cabf66ea3">

Is there a specific Matlab and Cplex version to run DEMETER?

**Comment by almut-heinken** [comment]
Hello,
sorry, there has been a recent change to the function and this line needs to be changed to
[debuggingReport, fixedModels, failedModels]=runDebuggingTools(refinedFolder,testResultsFolder,inputDataFolder,infoFilePath,reconVersion,'numWorkers',numWorkers);
I will fix this in the tutorial.

**Comment by AngelRuizMoreno** [comment]
I apply the proposed solution to the tutorial and confirmed it works.

<img width="895" alt="image" src="https://github.com/opencobra/COBRA.papers/assets/34551143/d2c198bb-5296-4d3c-9360-e9255e99fbe6">

The result is "All models passed all text. Exiting debugging tool".

Thank you. Best wishes.
